### ISSUE TITLE
read_elan() not working with some files

### ISSUE THREAD

**Issue by Xenomirant** [borstell/signglossR#3]
Function crashes with some files, especially containing single annotation tier, giving such reports

*Error: Problem with `mutate()` column `start_frame`.
i `start_frame = floor(start/fps)`.
i `start_frame` must be size 89 or 1, not 0.*

Also I think it makes sense to let you know that there're packages as 

*https://github.com/dalejbarr/elan* 

and

*https://github.com/oliverehmer/act*

that has some fuctions that may seem useful for parsing elan files

**Comment by borstell** [comment]
Thanks for the feedback! I assume this is caused by an incorrect video frame estimation based on either incorrectly reading the fps of the video, or annotation cells starting at (close to) zero. The frame position estimation is mostly redundant in this function anyway so I have removed it and pushed an update without it, hopefully working better now.

Thanks also for the suggested packages! I'm sure these (and perhaps other) packages may be better optimized for reading ELAN files, I wrote my own mostly to output the data in a format useful to my own research and other functions in the package.
